name: Docker Build and Push

on:
  push:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Docker Login
      uses: docker/login-action@v2.1.0
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push to docker
      env:
        TAG: "${{ secrets.DOCKERHUB_USERNAME }}/http-forwarder"
        TAGV: "$TAG:${{ github.ref_name }}"
      run: |
          echo "github.ref_type: ${{ github.ref_type }}"
          echo "github.ref_name: ${{ github.ref_name }}"
          echo "TAG: $TAG"
          echo "TAGV: $TAGV"
          docker build -t $TAG .
          docker push $TAG
          [ "${{ github.ref_type }}" == "tag" ] && docker tag $TAG %TAV && docker push $TAGV
